# Licensed under the Apache-2.0 license

[package]
name = "caliptra-mcu-spdm-vdm-handler"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []
device-ownership-transfer = []
ocp-lock = ["caliptra-mcu-common-commands/ocp-lock"]

[dependencies]
caliptra-mcu-common-commands = { workspace = true }
caliptra-mcu-spdm-traits = { workspace = true }
caliptra-mcu-spdm-codec = { workspace = true }
caliptra-mcu-spdm-errors = { workspace = true }
caliptra-mcu-mbox-common = { workspace = true }
mcu-error = { workspace = true }
zerocopy = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
mcu-caliptra-api = { workspace = true, features = ["mailbox-io"] }
