// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 37ccfe938398b47a86a08f0f411d5b863347ba39
//
#![recursion_limit = "512"]
#![no_std]
pub mod defines;
pub mod el2_pic_ctrl;
pub mod fuses;
pub mod i3c;
pub mod main_flash_ctrl;
pub mod mbox;
pub mod mci;
pub mod otp_ctrl;
pub mod recovery_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
