// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at a621fff9df7015821eda6f7f73265fef74a01375
//
#![recursion_limit = "256"]
#![no_std]
pub mod defines;
pub mod el2_pic_ctrl;
pub mod entropy_src;
pub mod fuses;
pub mod i3c;
pub mod main_flash_ctrl;
pub mod mbox;
pub mod otp_ctrl;
pub mod recovery_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
