// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 37ccfe938398b47a86a08f0f411d5b863347ba39
//
pub const RECOVERY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
