// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 2ec4914686d656467fae8ff40ee7da03ee6f5ec3
//
pub const RECOVERY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
