// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 4f006115433f926f4e599bc8718a39168f70ce5f
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
