// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at fb99e5f5aadf5685badae3ea453e72b55be9328c
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait I3cPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn read_dat(&mut self, _index: usize) -> caliptra_emu_types::RvData {
        0
    }
    fn write_dat(&mut self, _val: caliptra_emu_types::RvData, _index: usize) {}
    fn read_dct(&mut self, _index: usize) -> caliptra_emu_types::RvData {
        0
    }
    fn write_dct(&mut self, _val: caliptra_emu_types::RvData, _index: usize) {}
    fn read_i3c_base_hci_version(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_base_hc_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::HcControl::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_hc_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::HcControl::Register,
        >,
    ) {
    }
    fn read_i3c_base_controller_device_addr(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ControllerDeviceAddr::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_controller_device_addr(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::ControllerDeviceAddr::Register,
        >,
    ) {
    }
    fn read_i3c_base_hc_capabilities(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::HcCapabilities::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_reset_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ResetControl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_reset_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::ResetControl::Register,
        >,
    ) {
    }
    fn read_i3c_base_present_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PresentState::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_intr_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IntrStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_intr_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IntrStatus::Register,
        >,
    ) {
    }
    fn read_i3c_base_intr_status_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IntrStatusEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_intr_status_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IntrStatusEnable::Register,
        >,
    ) {
    }
    fn read_i3c_base_intr_signal_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IntrSignalEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_intr_signal_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IntrSignalEnable::Register,
        >,
    ) {
    }
    fn write_i3c_base_intr_force(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IntrForce::Register,
        >,
    ) {
    }
    fn read_i3c_base_dat_section_offset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DatSectionOffset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_dct_section_offset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DctSectionOffset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_dct_section_offset(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DctSectionOffset::Register,
        >,
    ) {
    }
    fn read_i3c_base_ring_headers_section_offset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::RingHeadersSectionOffset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_pio_section_offset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PioSectionOffset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_ext_caps_section_offset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtCapsSectionOffset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_int_ctrl_cmds_en(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IntCtrlCmdsEn::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_base_ibi_notify_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IbiNotifyCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_ibi_notify_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IbiNotifyCtrl::Register,
        >,
    ) {
    }
    fn read_i3c_base_ibi_data_abort_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IbiDataAbortCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_ibi_data_abort_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IbiDataAbortCtrl::Register,
        >,
    ) {
    }
    fn read_i3c_base_dev_ctx_base_lo(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DevCtxBaseLo::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_dev_ctx_base_lo(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DevCtxBaseLo::Register,
        >,
    ) {
    }
    fn read_i3c_base_dev_ctx_base_hi(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DevCtxBaseHi::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_base_dev_ctx_base_hi(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DevCtxBaseHi::Register,
        >,
    ) {
    }
    fn read_i3c_base_dev_ctx_sg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::DevCtxSg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_command_port(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_piocontrol_response_port(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_piocontrol_tx_data_port(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_piocontrol_rx_data_port(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_piocontrol_ibi_port(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_piocontrol_queue_thld_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::QueueThldCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_queue_thld_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::QueueThldCtrl::Register,
        >,
    ) {
    }
    fn read_piocontrol_data_buffer_thld_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DataBufferThldCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_data_buffer_thld_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DataBufferThldCtrl::Register,
        >,
    ) {
    }
    fn read_piocontrol_queue_size(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::QueueSize::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_piocontrol_alt_queue_size(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::AltQueueSize::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_piocontrol_pio_intr_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PioIntrStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_pio_intr_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::PioIntrStatus::Register,
        >,
    ) {
    }
    fn read_piocontrol_pio_intr_status_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PioIntrStatusEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_pio_intr_status_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::PioIntrStatusEnable::Register,
        >,
    ) {
    }
    fn read_piocontrol_pio_intr_signal_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PioIntrSignalEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_pio_intr_signal_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::PioIntrSignalEnable::Register,
        >,
    ) {
    }
    fn write_piocontrol_pio_intr_force(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::PioIntrForce::Register,
        >,
    ) {
    }
    fn read_piocontrol_pio_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::PioControl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_piocontrol_pio_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::PioControl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_extcap_header(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtcapHeader::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_sec_fw_recovery_if_prot_cap_0(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_prot_cap_1(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_prot_cap_2(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::ProtCap2::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_prot_cap_2(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::ProtCap2::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_prot_cap_3(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::ProtCap3::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_prot_cap_3(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::ProtCap3::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_device_id_0(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::DeviceId0::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_0(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DeviceId0::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_device_id_1(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_1(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_sec_fw_recovery_if_device_id_2(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_2(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_sec_fw_recovery_if_device_id_3(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_3(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_sec_fw_recovery_if_device_id_4(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_4(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_sec_fw_recovery_if_device_id_5(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_id_5(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_sec_fw_recovery_if_device_id_reserved(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_device_status_0(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DeviceStatus0::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_status_0(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DeviceStatus0::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_device_status_1(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DeviceStatus1::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_status_1(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DeviceStatus1::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_device_reset(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::DeviceReset::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_device_reset(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::DeviceReset::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_recovery_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::RecoveryCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_recovery_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::RecoveryCtrl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_recovery_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::RecoveryStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_recovery_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::RecoveryStatus::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_hw_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::HwStatus::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_hw_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::HwStatus::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_0(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IndirectFifoCtrl0::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_0(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::IndirectFifoCtrl0::Register,
        >,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_1(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_1(
        &mut self,
        _val: caliptra_emu_types::RvData,
    ) {
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_0(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IndirectFifoStatus0::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_1(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_2(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_3(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_4(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_reserved(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_sec_fw_recovery_if_indirect_fifo_data(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_stdby_ctrl_mode_extcap_header(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtcapHeader::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrControl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrControl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_device_addr(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrDeviceAddr::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_device_addr(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrDeviceAddr::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_capabilities(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrCapabilities::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_char(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrVirtualDeviceChar::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_char(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrVirtualDeviceChar::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrStatus::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_device_char(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrDeviceChar::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_device_char(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrDeviceChar::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_device_pid_lo(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_device_pid_lo(
        &mut self,
        _val: caliptra_emu_types::RvData,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrIntrStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrIntrStatus::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_pid_lo(
        &mut self,
    ) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_pid_lo(
        &mut self,
        _val: caliptra_emu_types::RvData,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_signal_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrIntrSignalEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_signal_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrIntrSignalEnable::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_force(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrIntrForce::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_force(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrIntrForce::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_getcaps(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrCccConfigGetcaps::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_getcaps(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrCccConfigGetcaps::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_rstact_params(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrCccConfigRstactParams::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_rstact_params(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrCccConfigRstactParams::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_stby_cr_virt_device_addr(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::StbyCrVirtDeviceAddr::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_stdby_ctrl_mode_stby_cr_virt_device_addr(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::StbyCrVirtDeviceAddr::Register,
        >,
    ) {
    }
    fn read_i3c_ec_stdby_ctrl_mode_rsvd_3(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_stdby_ctrl_mode_rsvd_3(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_tti_extcap_header(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtcapHeader::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_tti_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::sha512_acc::bits::Control::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::sha512_acc::bits::Control::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::lc_ctrl::bits::Status::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_tti_tti_reset_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::TtiResetControl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_tti_reset_control(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TtiResetControl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_interrupt_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::InterruptStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_interrupt_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::InterruptStatus::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_interrupt_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::InterruptEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_interrupt_enable(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::InterruptEnable::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_interrupt_force(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::InterruptForce::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_interrupt_force(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::InterruptForce::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_rx_desc_queue_port(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_i3c_ec_tti_rx_data_port(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_tti_tx_desc_queue_port(&mut self, _val: caliptra_emu_types::RvData) {}
    fn write_i3c_ec_tti_tx_data_port(&mut self, _val: caliptra_emu_types::RvData) {}
    fn write_i3c_ec_tti_tti_ibi_port(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_tti_tti_queue_size(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::TtiQueueSize::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_tti_ibi_tti_queue_size(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::IbiTtiQueueSize::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_tti_tti_queue_thld_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::TtiQueueThldCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_tti_queue_thld_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TtiQueueThldCtrl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_tti_tti_data_buffer_thld_ctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::TtiDataBufferThldCtrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_tti_tti_data_buffer_thld_ctrl(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TtiDataBufferThldCtrl::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_extcap_header(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtcapHeader::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_control(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_control(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_status(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_status(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_rec_intf_cfg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::RecIntfCfg::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_rec_intf_cfg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::RecIntfCfg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_rec_intf_reg_w1_c_access(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::RecIntfRegW1cAccess::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_rec_intf_reg_w1_c_access(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::RecIntfRegW1cAccess::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_2(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_2(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_3(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_3(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_soc_pad_conf(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::SocPadConf::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_soc_pad_conf(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::SocPadConf::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_soc_pad_attr(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::SocPadAttr::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_soc_pad_attr(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::SocPadAttr::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_feature_2(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_feature_2(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_soc_mgmt_feature_3(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_soc_mgmt_feature_3(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_t_r_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TRReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_r_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TRReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_f_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TFReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_f_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TFReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_su_dat_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TSuDatReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_su_dat_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TSuDatReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_hd_dat_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::THdDatReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_hd_dat_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::THdDatReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_high_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::THighReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_high_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::THighReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_low_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TLowReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_low_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TLowReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_hd_sta_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::THdStaReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_hd_sta_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::THdStaReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_su_sta_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TSuStaReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_su_sta_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TSuStaReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_su_sto_reg(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::i3c::bits::TSuStoReg::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_i3c_ec_soc_mgmt_if_t_su_sto_reg(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::i3c::bits::TSuStoReg::Register,
        >,
    ) {
    }
    fn read_i3c_ec_soc_mgmt_if_t_free_reg(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_t_free_reg(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_t_aval_reg(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_t_aval_reg(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_soc_mgmt_if_t_idle_reg(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_i3c_ec_soc_mgmt_if_t_idle_reg(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_i3c_ec_ctrl_cfg_extcap_header(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ExtcapHeader::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_i3c_ec_ctrl_cfg_controller_config(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::i3c::bits::ControllerConfig::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
}
pub struct I3cBus {
    pub periph: Box<dyn I3cPeripheral>,
}
impl caliptra_emu_bus::Bus for I3cBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0x400..0x800 => Ok(self.periph.read_dat((addr as usize - 0x400) / 4)),
            0x800..0x1000 => Ok(self.periph.read_dct((addr as usize - 0x800) / 4)),
            0..4 => Ok(self.periph.read_i3c_base_hci_version()),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_hc_control().reg.get(),
            )),
            8..0xc => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_controller_device_addr().reg.get(),
            )),
            0xc..0x10 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_hc_capabilities().reg.get(),
            )),
            0x10..0x14 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_reset_control().reg.get(),
            )),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_present_state().reg.get(),
            )),
            0x20..0x24 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_intr_status().reg.get(),
            )),
            0x24..0x28 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_intr_status_enable().reg.get(),
            )),
            0x28..0x2c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_intr_signal_enable().reg.get(),
            )),
            0x30..0x34 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_dat_section_offset().reg.get(),
            )),
            0x34..0x38 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_dct_section_offset().reg.get(),
            )),
            0x38..0x3c => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_base_ring_headers_section_offset()
                    .reg
                    .get(),
            )),
            0x3c..0x40 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_pio_section_offset().reg.get(),
            )),
            0x40..0x44 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_base_ext_caps_section_offset()
                    .reg
                    .get(),
            )),
            0x4c..0x50 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_int_ctrl_cmds_en().reg.get(),
            )),
            0x58..0x5c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_ibi_notify_ctrl().reg.get(),
            )),
            0x5c..0x60 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_ibi_data_abort_ctrl().reg.get(),
            )),
            0x60..0x64 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_dev_ctx_base_lo().reg.get(),
            )),
            0x64..0x68 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_dev_ctx_base_hi().reg.get(),
            )),
            0x68..0x6c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_base_dev_ctx_sg().reg.get(),
            )),
            0x84..0x88 => Ok(self.periph.read_piocontrol_response_port()),
            0x88..0x8c => Ok(self.periph.read_piocontrol_rx_data_port()),
            0x8c..0x90 => Ok(self.periph.read_piocontrol_ibi_port()),
            0x90..0x94 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_piocontrol_queue_thld_ctrl().reg.get(),
            )),
            0x94..0x98 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_piocontrol_data_buffer_thld_ctrl()
                    .reg
                    .get(),
            )),
            0x98..0x9c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_piocontrol_queue_size().reg.get(),
            )),
            0x9c..0xa0 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_piocontrol_alt_queue_size().reg.get(),
            )),
            0xa0..0xa4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_piocontrol_pio_intr_status().reg.get(),
            )),
            0xa4..0xa8 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_piocontrol_pio_intr_status_enable()
                    .reg
                    .get(),
            )),
            0xa8..0xac => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_piocontrol_pio_intr_signal_enable()
                    .reg
                    .get(),
            )),
            0xb0..0xb4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_piocontrol_pio_control().reg.get(),
            )),
            0x100..0x104 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_extcap_header()
                    .reg
                    .get(),
            )),
            0x104..0x108 => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_prot_cap_0()),
            0x108..0x10c => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_prot_cap_1()),
            0x10c..0x110 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_prot_cap_2()
                    .reg
                    .get(),
            )),
            0x110..0x114 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_prot_cap_3()
                    .reg
                    .get(),
            )),
            0x114..0x118 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_device_id_0()
                    .reg
                    .get(),
            )),
            0x118..0x11c => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_device_id_1()),
            0x11c..0x120 => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_device_id_2()),
            0x120..0x124 => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_device_id_3()),
            0x124..0x128 => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_device_id_4()),
            0x128..0x12c => Ok(self.periph.read_i3c_ec_sec_fw_recovery_if_device_id_5()),
            0x12c..0x130 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_device_id_reserved()),
            0x130..0x134 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_device_status_0()
                    .reg
                    .get(),
            )),
            0x134..0x138 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_device_status_1()
                    .reg
                    .get(),
            )),
            0x138..0x13c => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_device_reset()
                    .reg
                    .get(),
            )),
            0x13c..0x140 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_recovery_ctrl()
                    .reg
                    .get(),
            )),
            0x140..0x144 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_recovery_status()
                    .reg
                    .get(),
            )),
            0x144..0x148 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_hw_status()
                    .reg
                    .get(),
            )),
            0x148..0x14c => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_0()
                    .reg
                    .get(),
            )),
            0x14c..0x150 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_1()),
            0x150..0x154 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_0()
                    .reg
                    .get(),
            )),
            0x154..0x158 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_1()),
            0x158..0x15c => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_2()),
            0x15c..0x160 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_3()),
            0x160..0x164 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_status_4()),
            0x164..0x168 => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_reserved()),
            0x168..0x16c => Ok(self
                .periph
                .read_i3c_ec_sec_fw_recovery_if_indirect_fifo_data()),
            0x180..0x184 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_extcap_header()
                    .reg
                    .get(),
            )),
            0x184..0x188 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_control()
                    .reg
                    .get(),
            )),
            0x188..0x18c => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_device_addr()
                    .reg
                    .get(),
            )),
            0x18c..0x190 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_capabilities()
                    .reg
                    .get(),
            )),
            0x190..0x194 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_char()
                    .reg
                    .get(),
            )),
            0x194..0x198 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_status()
                    .reg
                    .get(),
            )),
            0x198..0x19c => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_device_char()
                    .reg
                    .get(),
            )),
            0x19c..0x1a0 => Ok(self
                .periph
                .read_i3c_ec_stdby_ctrl_mode_stby_cr_device_pid_lo()),
            0x1a0..0x1a4 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_status()
                    .reg
                    .get(),
            )),
            0x1a4..0x1a8 => Ok(self
                .periph
                .read_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_pid_lo()),
            0x1a8..0x1ac => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_signal_enable()
                    .reg
                    .get(),
            )),
            0x1ac..0x1b0 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_intr_force()
                    .reg
                    .get(),
            )),
            0x1b0..0x1b4 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_getcaps()
                    .reg
                    .get(),
            )),
            0x1b4..0x1b8 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_rstact_params()
                    .reg
                    .get(),
            )),
            0x1b8..0x1bc => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_stdby_ctrl_mode_stby_cr_virt_device_addr()
                    .reg
                    .get(),
            )),
            0x1bc..0x1c0 => Ok(self.periph.read_i3c_ec_stdby_ctrl_mode_rsvd_3()),
            0x1c0..0x1c4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_extcap_header().reg.get(),
            )),
            0x1c4..0x1c8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_control().reg.get(),
            )),
            0x1c8..0x1cc => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_status().reg.get(),
            )),
            0x1cc..0x1d0 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_tti_reset_control().reg.get(),
            )),
            0x1d0..0x1d4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_interrupt_status().reg.get(),
            )),
            0x1d4..0x1d8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_interrupt_enable().reg.get(),
            )),
            0x1d8..0x1dc => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_interrupt_force().reg.get(),
            )),
            0x1dc..0x1e0 => Ok(self.periph.read_i3c_ec_tti_rx_desc_queue_port()),
            0x1e0..0x1e4 => Ok(self.periph.read_i3c_ec_tti_rx_data_port()),
            0x1f0..0x1f4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_tti_queue_size().reg.get(),
            )),
            0x1f4..0x1f8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_ibi_tti_queue_size().reg.get(),
            )),
            0x1f8..0x1fc => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_tti_tti_queue_thld_ctrl().reg.get(),
            )),
            0x1fc..0x200 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_tti_tti_data_buffer_thld_ctrl()
                    .reg
                    .get(),
            )),
            0x200..0x204 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_soc_mgmt_if_extcap_header()
                    .reg
                    .get(),
            )),
            0x204..0x208 => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_control()),
            0x208..0x20c => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_status()),
            0x20c..0x210 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_rec_intf_cfg().reg.get(),
            )),
            0x210..0x214 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_soc_mgmt_if_rec_intf_reg_w1_c_access()
                    .reg
                    .get(),
            )),
            0x214..0x218 => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_2()),
            0x218..0x21c => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_3()),
            0x21c..0x220 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_soc_pad_conf().reg.get(),
            )),
            0x220..0x224 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_soc_pad_attr().reg.get(),
            )),
            0x224..0x228 => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_feature_2()),
            0x228..0x22c => Ok(self.periph.read_i3c_ec_soc_mgmt_if_soc_mgmt_feature_3()),
            0x22c..0x230 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_r_reg().reg.get(),
            )),
            0x230..0x234 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_f_reg().reg.get(),
            )),
            0x234..0x238 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_su_dat_reg().reg.get(),
            )),
            0x238..0x23c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_hd_dat_reg().reg.get(),
            )),
            0x23c..0x240 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_high_reg().reg.get(),
            )),
            0x240..0x244 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_low_reg().reg.get(),
            )),
            0x244..0x248 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_hd_sta_reg().reg.get(),
            )),
            0x248..0x24c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_su_sta_reg().reg.get(),
            )),
            0x24c..0x250 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_soc_mgmt_if_t_su_sto_reg().reg.get(),
            )),
            0x250..0x254 => Ok(self.periph.read_i3c_ec_soc_mgmt_if_t_free_reg()),
            0x254..0x258 => Ok(self.periph.read_i3c_ec_soc_mgmt_if_t_aval_reg()),
            0x258..0x25c => Ok(self.periph.read_i3c_ec_soc_mgmt_if_t_idle_reg()),
            0x260..0x264 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_i3c_ec_ctrl_cfg_extcap_header().reg.get(),
            )),
            0x264..0x268 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_i3c_ec_ctrl_cfg_controller_config()
                    .reg
                    .get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0x400..0x800 => {
                self.periph.write_dat(val, (addr as usize - 0x400) / 4);
                Ok(())
            }
            0x800..0x1000 => {
                self.periph.write_dct(val, (addr as usize - 0x800) / 4);
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_i3c_base_hc_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph.write_i3c_base_controller_device_addr(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x10..0x14 => {
                self.periph
                    .write_i3c_base_reset_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x20..0x24 => {
                self.periph
                    .write_i3c_base_intr_status(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x24..0x28 => {
                self.periph.write_i3c_base_intr_status_enable(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x28..0x2c => {
                self.periph.write_i3c_base_intr_signal_enable(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x2c..0x30 => {
                self.periph
                    .write_i3c_base_intr_force(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x34..0x38 => {
                self.periph.write_i3c_base_dct_section_offset(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x58..0x5c => {
                self.periph
                    .write_i3c_base_ibi_notify_ctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x5c..0x60 => {
                self.periph.write_i3c_base_ibi_data_abort_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x60..0x64 => {
                self.periph
                    .write_i3c_base_dev_ctx_base_lo(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x64..0x68 => {
                self.periph
                    .write_i3c_base_dev_ctx_base_hi(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x80..0x84 => {
                self.periph.write_piocontrol_command_port(val);
                Ok(())
            }
            0x88..0x8c => {
                self.periph.write_piocontrol_tx_data_port(val);
                Ok(())
            }
            0x90..0x94 => {
                self.periph.write_piocontrol_queue_thld_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x94..0x98 => {
                self.periph.write_piocontrol_data_buffer_thld_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0xa0..0xa4 => {
                self.periph.write_piocontrol_pio_intr_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0xa4..0xa8 => {
                self.periph.write_piocontrol_pio_intr_status_enable(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0xa8..0xac => {
                self.periph.write_piocontrol_pio_intr_signal_enable(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0xac..0xb0 => {
                self.periph
                    .write_piocontrol_pio_intr_force(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xb0..0xb4 => {
                self.periph
                    .write_piocontrol_pio_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x10c..0x110 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_prot_cap_2(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x110..0x114 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_prot_cap_3(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x114..0x118 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_0(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x118..0x11c => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_1(val);
                Ok(())
            }
            0x11c..0x120 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_2(val);
                Ok(())
            }
            0x120..0x124 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_3(val);
                Ok(())
            }
            0x124..0x128 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_4(val);
                Ok(())
            }
            0x128..0x12c => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_id_5(val);
                Ok(())
            }
            0x130..0x134 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_status_0(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x134..0x138 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_status_1(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x138..0x13c => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_device_reset(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x13c..0x140 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_recovery_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x140..0x144 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_recovery_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x144..0x148 => {
                self.periph.write_i3c_ec_sec_fw_recovery_if_hw_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x148..0x14c => {
                self.periph
                    .write_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_0(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x14c..0x150 => {
                self.periph
                    .write_i3c_ec_sec_fw_recovery_if_indirect_fifo_ctrl_1(val);
                Ok(())
            }
            0x184..0x188 => {
                self.periph.write_i3c_ec_stdby_ctrl_mode_stby_cr_control(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x188..0x18c => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_device_addr(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x190..0x194 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_char(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x194..0x198 => {
                self.periph.write_i3c_ec_stdby_ctrl_mode_stby_cr_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x198..0x19c => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_device_char(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x19c..0x1a0 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_device_pid_lo(val);
                Ok(())
            }
            0x1a0..0x1a4 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_status(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x1a4..0x1a8 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_virtual_device_pid_lo(val);
                Ok(())
            }
            0x1a8..0x1ac => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_signal_enable(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x1ac..0x1b0 => {
                self.periph.write_i3c_ec_stdby_ctrl_mode_stby_cr_intr_force(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1b0..0x1b4 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_getcaps(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x1b4..0x1b8 => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_ccc_config_rstact_params(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x1b8..0x1bc => {
                self.periph
                    .write_i3c_ec_stdby_ctrl_mode_stby_cr_virt_device_addr(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x1bc..0x1c0 => {
                self.periph.write_i3c_ec_stdby_ctrl_mode_rsvd_3(val);
                Ok(())
            }
            0x1c4..0x1c8 => {
                self.periph
                    .write_i3c_ec_tti_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x1cc..0x1d0 => {
                self.periph.write_i3c_ec_tti_tti_reset_control(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1d0..0x1d4 => {
                self.periph.write_i3c_ec_tti_interrupt_status(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1d4..0x1d8 => {
                self.periph.write_i3c_ec_tti_interrupt_enable(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1d8..0x1dc => {
                self.periph.write_i3c_ec_tti_interrupt_force(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1e4..0x1e8 => {
                self.periph.write_i3c_ec_tti_tx_desc_queue_port(val);
                Ok(())
            }
            0x1e8..0x1ec => {
                self.periph.write_i3c_ec_tti_tx_data_port(val);
                Ok(())
            }
            0x1ec..0x1f0 => {
                self.periph.write_i3c_ec_tti_tti_ibi_port(val);
                Ok(())
            }
            0x1f8..0x1fc => {
                self.periph.write_i3c_ec_tti_tti_queue_thld_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x1fc..0x200 => {
                self.periph.write_i3c_ec_tti_tti_data_buffer_thld_ctrl(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x204..0x208 => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_control(val);
                Ok(())
            }
            0x208..0x20c => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_status(val);
                Ok(())
            }
            0x20c..0x210 => {
                self.periph.write_i3c_ec_soc_mgmt_if_rec_intf_cfg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x210..0x214 => {
                self.periph
                    .write_i3c_ec_soc_mgmt_if_rec_intf_reg_w1_c_access(
                        caliptra_emu_bus::ReadWriteRegister::new(val),
                    );
                Ok(())
            }
            0x214..0x218 => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_2(val);
                Ok(())
            }
            0x218..0x21c => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_rsvd_3(val);
                Ok(())
            }
            0x21c..0x220 => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_pad_conf(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x220..0x224 => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_pad_attr(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x224..0x228 => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_feature_2(val);
                Ok(())
            }
            0x228..0x22c => {
                self.periph.write_i3c_ec_soc_mgmt_if_soc_mgmt_feature_3(val);
                Ok(())
            }
            0x22c..0x230 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_r_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x230..0x234 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_f_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x234..0x238 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_su_dat_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x238..0x23c => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_hd_dat_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x23c..0x240 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_high_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x240..0x244 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_low_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x244..0x248 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_hd_sta_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x248..0x24c => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_su_sta_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x24c..0x250 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_su_sto_reg(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                );
                Ok(())
            }
            0x250..0x254 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_free_reg(val);
                Ok(())
            }
            0x254..0x258 => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_aval_reg(val);
                Ok(())
            }
            0x258..0x25c => {
                self.periph.write_i3c_ec_soc_mgmt_if_t_idle_reg(val);
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
