// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 37ccfe938398b47a86a08f0f411d5b863347ba39
//
pub mod el2_pic;
pub mod i3c;
pub mod main_flash;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod recovery_flash;
pub mod root_bus;
pub mod sha512_acc;
pub mod soc;
