// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 4f006115433f926f4e599bc8718a39168f70ce5f
//
//
// Warning: caliptra-ss was dirty:?? src/integration/rtl/html/
//
pub mod el2_pic;
pub mod i3c;
pub mod lc;
pub mod main_flash;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod recovery_flash;
pub mod root_bus;
pub mod sha512_acc;
pub mod soc;
