// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 4f006115433f926f4e599bc8718a39168f70ce5f
//
//
// Warning: caliptra-ss was dirty:?? src/integration/rtl/html/
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait MainFlashPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<emulator_bus::Ram>>) {}
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn read_fl_interrupt_state(
        &mut self,
    ) -> emulator_bus::ReadWriteRegister<
        u32,
        registers_generated::main_flash_ctrl::bits::FlInterruptState::Register,
    > {
        emulator_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_interrupt_state(
        &mut self,
        _val: emulator_bus::ReadWriteRegister<
            u32,
            registers_generated::main_flash_ctrl::bits::FlInterruptState::Register,
        >,
    ) {
    }
    fn read_fl_interrupt_enable(
        &mut self,
    ) -> emulator_bus::ReadWriteRegister<
        u32,
        registers_generated::main_flash_ctrl::bits::FlInterruptEnable::Register,
    > {
        emulator_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_interrupt_enable(
        &mut self,
        _val: emulator_bus::ReadWriteRegister<
            u32,
            registers_generated::main_flash_ctrl::bits::FlInterruptEnable::Register,
        >,
    ) {
    }
    fn read_page_size(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_page_size(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_page_num(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_page_num(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_page_addr(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_page_addr(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_fl_control(
        &mut self,
    ) -> emulator_bus::ReadWriteRegister<
        u32,
        registers_generated::main_flash_ctrl::bits::FlControl::Register,
    > {
        emulator_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_control(
        &mut self,
        _val: emulator_bus::ReadWriteRegister<
            u32,
            registers_generated::main_flash_ctrl::bits::FlControl::Register,
        >,
    ) {
    }
    fn read_op_status(
        &mut self,
    ) -> emulator_bus::ReadWriteRegister<
        u32,
        registers_generated::main_flash_ctrl::bits::OpStatus::Register,
    > {
        emulator_bus::ReadWriteRegister::new(0)
    }
    fn write_op_status(
        &mut self,
        _val: emulator_bus::ReadWriteRegister<
            u32,
            registers_generated::main_flash_ctrl::bits::OpStatus::Register,
        >,
    ) {
    }
    fn read_ctrl_regwen(
        &mut self,
    ) -> emulator_bus::ReadWriteRegister<
        u32,
        registers_generated::main_flash_ctrl::bits::CtrlRegwen::Register,
    > {
        emulator_bus::ReadWriteRegister::new(0)
    }
}
pub struct MainFlashBus {
    pub periph: Box<dyn MainFlashPeripheral>,
}
impl emulator_bus::Bus for MainFlashBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, emulator_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(emulator_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_interrupt_state().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_interrupt_enable().reg.get(),
            )),
            8..0xc => Ok(self.periph.read_page_size()),
            0xc..0x10 => Ok(self.periph.read_page_num()),
            0x10..0x14 => Ok(self.periph.read_page_addr()),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_control().reg.get(),
            )),
            0x18..0x1c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_op_status().reg.get(),
            )),
            0x1c..0x20 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ctrl_regwen().reg.get(),
            )),
            _ => Err(emulator_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), emulator_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(emulator_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..4 => {
                self.periph
                    .write_fl_interrupt_state(emulator_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_fl_interrupt_enable(emulator_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph.write_page_size(val);
                Ok(())
            }
            0xc..0x10 => {
                self.periph.write_page_num(val);
                Ok(())
            }
            0x10..0x14 => {
                self.periph.write_page_addr(val);
                Ok(())
            }
            0x14..0x18 => {
                self.periph
                    .write_fl_control(emulator_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x18..0x1c => {
                self.periph
                    .write_op_status(emulator_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            _ => Err(emulator_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
