// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at a621fff9df7015821eda6f7f73265fef74a01375
//
pub struct AutoRootBus {
    delegate: Option<Box<dyn emulator_bus::Bus>>,
    pub i3c_csr_periph: Option<crate::I3CCSR::I3ccsrBus>,
    pub mbox_periph: Option<crate::mbox::MboxBus>,
    pub sha512_acc_periph: Option<crate::sha512_acc::Sha512AccBus>,
    pub soc_periph: Option<crate::soc::SocBus>,
    pub el2_pic_periph: Option<crate::el2_pic::El2PicBus>,
}
impl AutoRootBus {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        delegate: Option<Box<dyn emulator_bus::Bus>>,
        i3c_csr_periph: Option<Box<dyn crate::I3CCSR::I3ccsrPeripheral>>,
        mbox_periph: Option<Box<dyn crate::mbox::MboxPeripheral>>,
        sha512_acc_periph: Option<Box<dyn crate::sha512_acc::Sha512AccPeripheral>>,
        soc_periph: Option<Box<dyn crate::soc::SocPeripheral>>,
        el2_pic_periph: Option<Box<dyn crate::el2_pic::El2PicPeripheral>>,
    ) -> Self {
        Self {
            delegate,
            i3c_csr_periph: i3c_csr_periph.map(|p| crate::I3CCSR::I3ccsrBus { periph: p }),
            mbox_periph: mbox_periph.map(|p| crate::mbox::MboxBus { periph: p }),
            sha512_acc_periph: sha512_acc_periph
                .map(|p| crate::sha512_acc::Sha512AccBus { periph: p }),
            soc_periph: soc_periph.map(|p| crate::soc::SocBus { periph: p }),
            el2_pic_periph: el2_pic_periph.map(|p| crate::el2_pic::El2PicBus { periph: p }),
        }
    }
}
impl emulator_bus::Bus for AutoRootBus {
    fn read(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
    ) -> Result<emulator_types::RvData, emulator_bus::BusError> {
        let result = match addr {
            0x2000_4000..=0x2000_5988 => {
                if let Some(periph) = self.i3c_csr_periph.as_mut() {
                    periph.read(size, addr - 0x2000_4000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3002_0000..=0x3002_00b4 => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.read(size, addr - 0x3002_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3002_1000..=0x3002_289c => {
                if let Some(periph) = self.sha512_acc_periph.as_mut() {
                    periph.read(size, addr - 0x3002_1000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3003_0000..=0x3003_91c0 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.read(size, addr - 0x3003_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x6000_0000..=0x6000_f018 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.read(size, addr - 0x6000_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::LoadAccessFault),
        };
        if let Some(delegate) = self.delegate.as_mut() {
            match result {
                Err(emulator_bus::BusError::LoadAccessFault) => delegate.read(size, addr),
                _ => result,
            }
        } else {
            result
        }
    }
    fn write(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
        val: emulator_types::RvData,
    ) -> Result<(), emulator_bus::BusError> {
        let result = match addr {
            0x2000_4000..=0x2000_5988 => {
                if let Some(periph) = self.i3c_csr_periph.as_mut() {
                    periph.write(size, addr - 0x2000_4000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3002_0000..=0x3002_00b4 => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.write(size, addr - 0x3002_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3002_1000..=0x3002_289c => {
                if let Some(periph) = self.sha512_acc_periph.as_mut() {
                    periph.write(size, addr - 0x3002_1000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3003_0000..=0x3003_91c0 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.write(size, addr - 0x3003_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x6000_0000..=0x6000_f018 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.write(size, addr - 0x6000_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::StoreAccessFault),
        };
        if let Some(delegate) = self.delegate.as_mut() {
            match result {
                Err(emulator_bus::BusError::StoreAccessFault) => delegate.write(size, addr, val),
                _ => result,
            }
        } else {
            result
        }
    }
    fn poll(&mut self) {
        if let Some(periph) = self.i3c_csr_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.poll();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.poll();
        }
    }
    fn warm_reset(&mut self) {
        if let Some(periph) = self.i3c_csr_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.warm_reset();
        }
    }
    fn update_reset(&mut self) {
        if let Some(periph) = self.i3c_csr_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.update_reset();
        }
    }
}
