// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 2ec4914686d656467fae8ff40ee7da03ee6f5ec3
//
pub struct AutoRootBus {
    delegates: Vec<Box<dyn emulator_bus::Bus>>,
    pub dccm: emulator_bus::Ram,
    pub i3c_periph: Option<crate::i3c::I3cBus>,
    pub main_flash_periph: Option<crate::main_flash::MainFlashBus>,
    pub recovery_flash_periph: Option<crate::recovery_flash::RecoveryFlashBus>,
    pub otp_periph: Option<crate::otp::OtpBus>,
    pub mci_periph: Option<crate::mci::MciBus>,
    pub mbox_periph: Option<crate::mbox::MboxBus>,
    pub sha512_acc_periph: Option<crate::sha512_acc::Sha512AccBus>,
    pub soc_periph: Option<crate::soc::SocBus>,
    pub el2_pic_periph: Option<crate::el2_pic::El2PicBus>,
}
impl AutoRootBus {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        delegates: Vec<Box<dyn emulator_bus::Bus>>,
        i3c_periph: Option<Box<dyn crate::i3c::I3cPeripheral>>,
        main_flash_periph: Option<Box<dyn crate::main_flash::MainFlashPeripheral>>,
        recovery_flash_periph: Option<Box<dyn crate::recovery_flash::RecoveryFlashPeripheral>>,
        otp_periph: Option<Box<dyn crate::otp::OtpPeripheral>>,
        mci_periph: Option<Box<dyn crate::mci::MciPeripheral>>,
        mbox_periph: Option<Box<dyn crate::mbox::MboxPeripheral>>,
        sha512_acc_periph: Option<Box<dyn crate::sha512_acc::Sha512AccPeripheral>>,
        soc_periph: Option<Box<dyn crate::soc::SocPeripheral>>,
        el2_pic_periph: Option<Box<dyn crate::el2_pic::El2PicPeripheral>>,
    ) -> Self {
        Self {
            delegates,
            dccm: emulator_bus::Ram::new(vec![0; 16384u32 as usize]),
            i3c_periph: i3c_periph.map(|p| crate::i3c::I3cBus { periph: p }),
            main_flash_periph: main_flash_periph
                .map(|p| crate::main_flash::MainFlashBus { periph: p }),
            recovery_flash_periph: recovery_flash_periph
                .map(|p| crate::recovery_flash::RecoveryFlashBus { periph: p }),
            otp_periph: otp_periph.map(|p| crate::otp::OtpBus { periph: p }),
            mci_periph: mci_periph.map(|p| crate::mci::MciBus { periph: p }),
            mbox_periph: mbox_periph.map(|p| crate::mbox::MboxBus { periph: p }),
            sha512_acc_periph: sha512_acc_periph
                .map(|p| crate::sha512_acc::Sha512AccBus { periph: p }),
            soc_periph: soc_periph.map(|p| crate::soc::SocBus { periph: p }),
            el2_pic_periph: el2_pic_periph.map(|p| crate::el2_pic::El2PicBus { periph: p }),
        }
    }
}
impl emulator_bus::Bus for AutoRootBus {
    fn read(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
    ) -> Result<emulator_types::RvData, emulator_bus::BusError> {
        let result = match addr {
            0x5000_0000..=0x5000_3fff => self.dccm.read(size, addr - 0x5000_0000),
            0x2000_4000..=0x2000_5987 => {
                if let Some(periph) = self.i3c_periph.as_mut() {
                    periph.read(size, addr - 0x2000_4000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2000_8000..=0x2000_808f => {
                if let Some(periph) = self.main_flash_periph.as_mut() {
                    periph.read(size, addr - 0x2000_8000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2000_8800..=0x2000_888f => {
                if let Some(periph) = self.recovery_flash_periph.as_mut() {
                    periph.read(size, addr - 0x2000_8800)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2000_b000..=0x2000_b9db => {
                if let Some(periph) = self.otp_periph.as_mut() {
                    periph.read(size, addr - 0x2000_b000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2100_0000..=0x2101_7b1f => {
                if let Some(periph) = self.mci_periph.as_mut() {
                    periph.read(size, addr - 0x2100_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3002_0000..=0x3002_00db => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.read(size, addr - 0x3002_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3002_1000..=0x3002_289b => {
                if let Some(periph) = self.sha512_acc_periph.as_mut() {
                    periph.read(size, addr - 0x3002_1000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3003_0000..=0x3003_f703 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.read(size, addr - 0x3003_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x6000_0000..=0x6001_0403 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.read(size, addr - 0x6000_0000)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::LoadAccessFault),
        };
        if !matches!(result, Err(emulator_bus::BusError::LoadAccessFault)) {
            return result;
        }
        for delegate in self.delegates.iter_mut() {
            let result = delegate.read(size, addr);
            if !matches!(result, Err(emulator_bus::BusError::LoadAccessFault)) {
                return result;
            }
        }
        result
    }
    fn write(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
        val: emulator_types::RvData,
    ) -> Result<(), emulator_bus::BusError> {
        let result = match addr {
            0x5000_0000..=0x5000_3fff => self.dccm.write(size, addr - 0x5000_0000, val),
            0x2000_4000..=0x2000_5987 => {
                if let Some(periph) = self.i3c_periph.as_mut() {
                    periph.write(size, addr - 0x2000_4000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2000_8000..=0x2000_808f => {
                if let Some(periph) = self.main_flash_periph.as_mut() {
                    periph.write(size, addr - 0x2000_8000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2000_8800..=0x2000_888f => {
                if let Some(periph) = self.recovery_flash_periph.as_mut() {
                    periph.write(size, addr - 0x2000_8800, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2000_b000..=0x2000_b9db => {
                if let Some(periph) = self.otp_periph.as_mut() {
                    periph.write(size, addr - 0x2000_b000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2100_0000..=0x2101_7b1f => {
                if let Some(periph) = self.mci_periph.as_mut() {
                    periph.write(size, addr - 0x2100_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3002_0000..=0x3002_00db => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.write(size, addr - 0x3002_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3002_1000..=0x3002_289b => {
                if let Some(periph) = self.sha512_acc_periph.as_mut() {
                    periph.write(size, addr - 0x3002_1000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3003_0000..=0x3003_f703 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.write(size, addr - 0x3003_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x6000_0000..=0x6001_0403 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.write(size, addr - 0x6000_0000, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::StoreAccessFault),
        };
        if !matches!(result, Err(emulator_bus::BusError::StoreAccessFault)) {
            return result;
        }
        for delegate in self.delegates.iter_mut() {
            let result = delegate.write(size, addr, val);
            if !matches!(result, Err(emulator_bus::BusError::StoreAccessFault)) {
                return result;
            }
        }
        result
    }
    fn poll(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.main_flash_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.recovery_flash_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.otp_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.poll();
        }
        for delegate in self.delegates.iter_mut() {
            delegate.poll();
        }
    }
    fn warm_reset(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.main_flash_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.recovery_flash_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.otp_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.warm_reset();
        }
        for delegate in self.delegates.iter_mut() {
            delegate.warm_reset();
        }
    }
    fn update_reset(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.main_flash_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.recovery_flash_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.otp_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.update_reset();
        }
        for delegate in self.delegates.iter_mut() {
            delegate.update_reset();
        }
    }
    fn incoming_event(&mut self, event: std::rc::Rc<caliptra_emu_bus::Event>) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.main_flash_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.recovery_flash_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.otp_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.incoming_event(event.clone());
        }
        for delegate in self.delegates.iter_mut() {
            delegate.incoming_event(event.clone());
        }
    }
    fn register_outgoing_events(
        &mut self,
        sender: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
    ) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.main_flash_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.recovery_flash_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.otp_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.sha512_acc_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.register_outgoing_events(sender.clone());
        }
        for delegate in self.delegates.iter_mut() {
            delegate.register_outgoing_events(sender.clone());
        }
    }
}
