// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-rtl repo at 0e43b8e7011c1c8761e114bc949fcad6cf30538e
// , caliptra-ss repo at 9911c2b0e4bac9e4b48f6c2155c86cb116159734
// , and i3c-core repo at d5c715103f529ade0e5d375a53c5692daaa9c54b
//
pub struct AutoRootBus {
    delegate: Option<Box<dyn emulator_bus::Bus>>,
    pub i3c_periph: Option<crate::i3c::I3cBus>,
    pub spi_host_periph: Option<crate::spi_host::SpiHostBus>,
    pub uart_periph: Option<crate::uart::UartBus>,
    pub mci_periph: Option<crate::mci::MciBus>,
    pub mbox_periph: Option<crate::mbox::MboxBus>,
    pub soc_periph: Option<crate::soc::SocBus>,
    pub el2_pic_periph: Option<crate::el2_pic::El2PicBus>,
}
impl AutoRootBus {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        delegate: Option<Box<dyn emulator_bus::Bus>>,
        i3c_periph: Option<Box<dyn crate::i3c::I3cPeripheral>>,
        spi_host_periph: Option<Box<dyn crate::spi_host::SpiHostPeripheral>>,
        uart_periph: Option<Box<dyn crate::uart::UartPeripheral>>,
        mci_periph: Option<Box<dyn crate::mci::MciPeripheral>>,
        mbox_periph: Option<Box<dyn crate::mbox::MboxPeripheral>>,
        soc_periph: Option<Box<dyn crate::soc::SocPeripheral>>,
        el2_pic_periph: Option<Box<dyn crate::el2_pic::El2PicPeripheral>>,
    ) -> Self {
        Self {
            delegate,
            i3c_periph: i3c_periph.map(|p| crate::i3c::I3cBus { periph: p }),
            spi_host_periph: spi_host_periph.map(|p| crate::spi_host::SpiHostBus { periph: p }),
            uart_periph: uart_periph.map(|p| crate::uart::UartBus { periph: p }),
            mci_periph: mci_periph.map(|p| crate::mci::MciBus { periph: p }),
            mbox_periph: mbox_periph.map(|p| crate::mbox::MboxBus { periph: p }),
            soc_periph: soc_periph.map(|p| crate::soc::SocBus { periph: p }),
            el2_pic_periph: el2_pic_periph.map(|p| crate::el2_pic::El2PicBus { periph: p }),
        }
    }
}
impl emulator_bus::Bus for AutoRootBus {
    fn read(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
    ) -> Result<emulator_types::RvData, emulator_bus::BusError> {
        let result = match addr {
            0x1003_8100..=0x1003_9a88 => {
                if let Some(periph) = self.i3c_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2000_0000..=0x2000_01c0 => {
                if let Some(periph) = self.spi_host_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2000_1000..=0x2000_116c => {
                if let Some(periph) = self.uart_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x2005_0000..=0x2005_4770 => {
                if let Some(periph) = self.mci_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3002_0000..=0x3002_00b4 => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x3003_0000..=0x3003_91c0 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            0x6000_0000..=0x6000_f018 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.read(size, addr)
                } else {
                    Err(emulator_bus::BusError::LoadAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::LoadAccessFault),
        };
        if let Some(delegate) = self.delegate.as_mut() {
            match result {
                Err(emulator_bus::BusError::LoadAccessFault) => delegate.read(size, addr),
                _ => result,
            }
        } else {
            result
        }
    }
    fn write(
        &mut self,
        size: emulator_types::RvSize,
        addr: emulator_types::RvAddr,
        val: emulator_types::RvData,
    ) -> Result<(), emulator_bus::BusError> {
        let result = match addr {
            0x1003_8100..=0x1003_9a88 => {
                if let Some(periph) = self.i3c_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2000_0000..=0x2000_01c0 => {
                if let Some(periph) = self.spi_host_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2000_1000..=0x2000_116c => {
                if let Some(periph) = self.uart_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x2005_0000..=0x2005_4770 => {
                if let Some(periph) = self.mci_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3002_0000..=0x3002_00b4 => {
                if let Some(periph) = self.mbox_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x3003_0000..=0x3003_91c0 => {
                if let Some(periph) = self.soc_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            0x6000_0000..=0x6000_f018 => {
                if let Some(periph) = self.el2_pic_periph.as_mut() {
                    periph.write(size, addr, val)
                } else {
                    Err(emulator_bus::BusError::StoreAccessFault)
                }
            }
            _ => Err(emulator_bus::BusError::StoreAccessFault),
        };
        if let Some(delegate) = self.delegate.as_mut() {
            match result {
                Err(emulator_bus::BusError::StoreAccessFault) => delegate.write(size, addr, val),
                _ => result,
            }
        } else {
            result
        }
    }
    fn poll(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.spi_host_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.uart_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.poll();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.poll();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.poll();
        }
    }
    fn warm_reset(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.spi_host_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.uart_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.warm_reset();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.warm_reset();
        }
    }
    fn update_reset(&mut self) {
        if let Some(periph) = self.i3c_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.spi_host_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.uart_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.mci_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.mbox_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.soc_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(periph) = self.el2_pic_periph.as_mut() {
            periph.update_reset();
        }
        if let Some(delegate) = self.delegate.as_mut() {
            delegate.update_reset();
        }
    }
}
