// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at fb99e5f5aadf5685badae3ea453e72b55be9328c
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait SecondaryFlashPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut SecondaryFlashGenerated> {
        None
    }
    fn read_fl_interrupt_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlInterruptState::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_fl_interrupt_state();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_interrupt_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlInterruptState::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_fl_interrupt_state(val);
        }
    }
    fn read_fl_interrupt_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlInterruptEnable::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_fl_interrupt_enable();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_interrupt_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlInterruptEnable::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_fl_interrupt_enable(val);
        }
    }
    fn read_page_size(&mut self) -> caliptra_emu_types::RvData {
        if let Some(generated) = self.generated() {
            return generated.read_page_size();
        }
        0
    }
    fn write_page_size(&mut self, val: caliptra_emu_types::RvData) {
        if let Some(generated) = self.generated() {
            generated.write_page_size(val);
        }
    }
    fn read_page_num(&mut self) -> caliptra_emu_types::RvData {
        if let Some(generated) = self.generated() {
            return generated.read_page_num();
        }
        0
    }
    fn write_page_num(&mut self, val: caliptra_emu_types::RvData) {
        if let Some(generated) = self.generated() {
            generated.write_page_num(val);
        }
    }
    fn read_page_addr(&mut self) -> caliptra_emu_types::RvData {
        if let Some(generated) = self.generated() {
            return generated.read_page_addr();
        }
        0
    }
    fn write_page_addr(&mut self, val: caliptra_emu_types::RvData) {
        if let Some(generated) = self.generated() {
            generated.write_page_addr(val);
        }
    }
    fn read_fl_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlControl::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_fl_control();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_fl_control(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlControl::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_fl_control(val);
        }
    }
    fn read_op_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::OpStatus::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_op_status();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_op_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::OpStatus::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_op_status(val);
        }
    }
    fn read_ctrl_regwen(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::CtrlRegwen::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_ctrl_regwen();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
}
#[derive(Clone, Debug)]
pub struct SecondaryFlashGenerated {
    fl_interrupt_state: caliptra_emu_types::RvData,
    fl_interrupt_enable: caliptra_emu_types::RvData,
    page_size: caliptra_emu_types::RvData,
    page_num: caliptra_emu_types::RvData,
    page_addr: caliptra_emu_types::RvData,
    fl_control: caliptra_emu_types::RvData,
    op_status: caliptra_emu_types::RvData,
    ctrl_regwen: caliptra_emu_types::RvData,
}
impl Default for SecondaryFlashGenerated {
    fn default() -> Self {
        Self {
            fl_interrupt_state: 0 as caliptra_emu_types::RvData,
            fl_interrupt_enable: 0 as caliptra_emu_types::RvData,
            page_size: 0 as caliptra_emu_types::RvData,
            page_num: 0 as caliptra_emu_types::RvData,
            page_addr: 0 as caliptra_emu_types::RvData,
            fl_control: 0 as caliptra_emu_types::RvData,
            op_status: 0 as caliptra_emu_types::RvData,
            ctrl_regwen: 0 as caliptra_emu_types::RvData,
        }
    }
}
impl SecondaryFlashGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl SecondaryFlashPeripheral for SecondaryFlashGenerated {
    fn generated(&mut self) -> Option<&mut SecondaryFlashGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_fl_interrupt_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlInterruptState::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.fl_interrupt_state)
    }
    fn write_fl_interrupt_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlInterruptState::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.fl_interrupt_state;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        self.fl_interrupt_state = new_val;
    }
    fn read_fl_interrupt_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlInterruptEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.fl_interrupt_enable)
    }
    fn write_fl_interrupt_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlInterruptEnable::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.fl_interrupt_enable;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        self.fl_interrupt_enable = new_val;
    }
    fn read_page_size(&mut self) -> caliptra_emu_types::RvData {
        self.page_size
    }
    fn write_page_size(&mut self, val: caliptra_emu_types::RvData) {
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.page_size;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.page_size = new_val;
    }
    fn read_page_num(&mut self) -> caliptra_emu_types::RvData {
        self.page_num
    }
    fn write_page_num(&mut self, val: caliptra_emu_types::RvData) {
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.page_num;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.page_num = new_val;
    }
    fn read_page_addr(&mut self) -> caliptra_emu_types::RvData {
        self.page_addr
    }
    fn write_page_addr(&mut self, val: caliptra_emu_types::RvData) {
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.page_addr;
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.page_addr = new_val;
    }
    fn read_fl_control(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::FlControl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.fl_control)
    }
    fn write_fl_control(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::FlControl::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.fl_control;
        let mut new_val = current_val;
        new_val = (new_val & !(6 as caliptra_emu_types::RvData))
            | (write_val & (6 as caliptra_emu_types::RvData));
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        self.fl_control = new_val;
    }
    fn read_op_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::OpStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.op_status)
    }
    fn write_op_status(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::primary_flash_ctrl::bits::OpStatus::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.op_status;
        let mut new_val = current_val;
        new_val = (new_val & !(0xe as caliptra_emu_types::RvData))
            | (write_val & (0xe as caliptra_emu_types::RvData));
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        self.op_status = new_val;
    }
    fn read_ctrl_regwen(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::primary_flash_ctrl::bits::CtrlRegwen::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.ctrl_regwen)
    }
}
pub struct SecondaryFlashBus {
    pub periph: Box<dyn SecondaryFlashPeripheral>,
}
impl caliptra_emu_bus::Bus for SecondaryFlashBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_interrupt_state().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_interrupt_enable().reg.get(),
            )),
            8..0xc => Ok(self.periph.read_page_size()),
            0xc..0x10 => Ok(self.periph.read_page_num()),
            0x10..0x14 => Ok(self.periph.read_page_addr()),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_fl_control().reg.get(),
            )),
            0x18..0x1c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_op_status().reg.get(),
            )),
            0x1c..0x20 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ctrl_regwen().reg.get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..4 => {
                self.periph
                    .write_fl_interrupt_state(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_fl_interrupt_enable(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph.write_page_size(val);
                Ok(())
            }
            0xc..0x10 => {
                self.periph.write_page_num(val);
                Ok(())
            }
            0x10..0x14 => {
                self.periph.write_page_addr(val);
                Ok(())
            }
            0x14..0x18 => {
                self.periph
                    .write_fl_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x18..0x1c => {
                self.periph
                    .write_op_status(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x1c..0x20 => Ok(()),
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
